services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: wrascal
      DB_PASSWORD: wrascal
      DB_NAME: wrascal
      DB_SCHEMA: public
      DB_SSL: false
      NODE_ENV: development
      TYPEORM_SYNC: "true"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: wrascal
      POSTGRES_PASSWORD: wrascal
      POSTGRES_DB: wrascal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

